### ISSUE TITLE
Does not work on Windows XP

### ISSUE THREAD

**Issue by kurdtkobain** [coolstar/iOSToolchain4Win#1]
iToolchain ld fails 
"Entry Point Not Found - The procedure entry point GetFileInformationByHandleEx could not be located in the dynamic link library KERNEL32.dll"
That means this file was not compiles to run on Windows XP as that function is for Vista+

**Comment by kurdtkobain** [comment]
After some "Hexing" i was able to get it to work by using the same hack x-com uses with zernel.dll and fileextd.dll

X-COM Hack -> http://forums.steampowered.com/forums/showthread.php?t=2964408

Testing if my deb works on my 6.1.3 3g[s] now

EDIT: ok it works a bit of a hacky solution but works for me lol

**Comment by kurdtkobain** [comment]
Made a XP hack version 
[IOSToolchain4Win XP Hack](https://github.com/kurdtkobain/iOSToolchain4Win)

**Comment by coolstar** [comment]
Please create a new branch in git called "xp" and then send a pull request that adds the "xp" branch.

**Comment by coolstar** [comment]
Windows XP is no longer supported.
