### ISSUE TITLE
LD Errors

### ISSUE THREAD

**Issue by GroovyCarrot** [coolstar/iOSToolchain4Win#4]
Initially I was having an issue where LD was throwing the following error, I added -v to LDFLAGS to see what was going on and after chmod 0777 /tmp -R I was very puzzled why it was still happening:

$ make
Making all for tweak SBHTML...
 Linking tweak SBHTML...
clang version 3.5.0 (trunk 206471) (llvm/trunk 206470)
Target: arm64-apple-darwin11
Thread model: posix
 "/home/Jake/sbhtml/theos/toolchain/windows/iphone/bin/armv7-apple-darwin11-ld" -demangle -dynamic -dylib -arch armv7 -dylib_install_name /Library/MobileSubstrate/DynamicLibraries/SBHTML.dylib -iphoneos_version_min 7.1.0 -multiply_defined suppress -syslibroot /opt/theos/toolchain/windows/sdks/iPhoneOS7.1.sdk -ObjC -o /tmp/-26ce26.out -L/opt/theos/toolchain/windows/lib -lobjc -framework Foundation -framework CoreFoundation -framework Foundation -framework UIKit -framework CoreGraphics -framework QuartzCore -lMobileGestalt -lsubstrate obj/Tweak.xm.0c5dd894.o -arch_multiple -final_output obj/SBHTML.dylib.1b5b9d6a.unsigned -lc++ -lSystem
ld: can't open output file for writing: /tmp/-26ce26.out, errno=2 for architecture armv7
armv7-apple-darwin11-clang: error: linker command failed with exit code 1 (use -v to see invocation)
/opt/theos/toolchain/windows/makefiles/instance/library.mk:27: recipe for target 'obj/SBHTML.dylib.1b5b9d6a.unsigned' failed
make[2]: **\* [obj/SBHTML.dylib.1b5b9d6a.unsigned] Error 1
/opt/theos/toolchain/windows/makefiles/instance/library.mk:19: recipe for target 'internal-library-all_' failed
make[1]: **\* [internal-library-all_] Error 2
/opt/theos/toolchain/windows/makefiles/master/rules.mk:54: recipe for target 'SBHTML.all.tweak.variables' failed
make: **\* [SBHTML.all.tweak.variables] Error 2

So after asking for a second opinion it hit me that it might be trying to write to C:\tmp rather than cygwin's root /tmp but would only display /tmp due to it being a pseudo-unix enviroment. Sure enough creating a directory tmp in C:\ resolved the issue and so I figured it would well be worth mentioning here to anyone else struggling.

Unfortunately the issue didn't seem to be resolved as following that stage as I hadn't read that you still needed an ARM64 linker. Still for the time being I have an old intel laptop running OSX that I can do the building on, looking forward to seeing this toolchain fully updated.

Final note worth mentioning is that to successfully compile I have to point theos to the compiler manually in the makefile:
TARGET_CC = /opt/theos/toolchain/windows/iphone/bin/armv7-apple-darwin11-clang.exe
TARGET_CXX = /opt/theos/toolchain/windows/iphone/bin/armv7-apple-darwin11-clang++.exe

**Comment by coolstar** [comment]
arm64 support was added in https://github.com/coolstar/iOSToolchain4Win/tree/0b551911ec5163a792caee140a033ead1353b08a
